### ISSUE TITLE
Style Your Nick is not working with "Style Usernames" plugin

### ISSUE THREAD

**Issue by rockenren** [Destroy666x/MyBB-Style-Your-Nick#1]
It seems to SYN is not working when "Style Usernames" plugin (https://github.com/lukasamd/MyBB-Style_Usernames) installed and active. The username style will be always set as in group settings.

MyBB 1.8.4,

**Comment by Destroy666x** [comment]
@rockenren, do you mean this? https://github.com/lukasamd/MyBB-Style_Usernames
It worked fine on a forum for which it was initially made and I see no reason for it to not work. Make sure you're using 1.8 version fo that plugin.

Can't tell more without board URL and a testing account. Also, the inc/functions.php file contents would help.

**Comment by rockenren** [comment]
My bad, problem is not in Style Usernames plugin.
But plugin totally didnt work for me, even preview always show default pre-define username style

My inc/functions.php content: http://pastebin.com/u32SdkPX

**Comment by Destroy666x** [comment]
@rockenren, please read this: https://github.com/Destroy666x/MyBB-Style-Your-Nick#requirements

I guess you upgraded and overwrote the file losing all changes, you need to reactivate the plugin in that case. Have you reactivated it?

**Comment by rockenren** [comment]
No, I'm using this plugin for the first time.
Yes, I tried reactivation and even uninstallation. I've compared functions.php after deactivation-activation. They are exactly match, seems plugin cannot modify it somehow.

I'm kinda confused. I've tested on localhost and all things work ok, functions.php modified as intended.
Did this plugin require permissions set as 666 to functions.php? But I dont see erros in my apache error log.

**Comment by rockenren** [comment]
Yeah, silly me. Sorry.
Obviously, this plugin do some modifications in files, so functions.php must have permissions to write (666).

But there is no error or other messages relating to this kind of error. Could you please add this info in readme/installation guide at least?

This issue can be closed.

**Comment by Destroy666x** [comment]
> But there is no error or other messages relating to this kind of error. Could you please add this info in readme/installation guide at least?

@rockenren, this plugin uses a PluginLibrary function for core edits and besides checking if that function results in `false` (which I already do and it seems to work for me), I can't do anything. No idea why it didn't show any error for you - it may either be caused by outdated PluginLibrary (which version do you use?) or it works differently on newer PHP versions (which do you have?).

I'll do some more tests for the lack of error when I'll have time.

**Comment by rockenren** [comment]
I'm using PluginLibrary ver. 12 and PHP ver. 5.5.9.

**Comment by Destroy666x** [comment]
Ah, I see the problem, I may have fixed it locally, but apparently I haven't committed the `admin_redirect()` change here, which is required for the error to show. I'll fix it in the next version. Thanks for info.
