### ISSUE TITLE
Add background-repeat: no-repeat by default

### ISSUE THREAD

**Issue by rockenren** [Destroy666x/MyBB-Style-Your-Nick#2]
When enabling background repeating, the CSS rule "background-repeat: repeat" is added.
But, when this option is disabled, no css rule applied and we can only rely on browser implementation.

I think this is wrong behavior, and "background-repeat: no-repeat" can be added when in default state.

**Comment by Destroy666x** [comment]
I'll add it.

**Comment by Destroy666x** [comment]
Fixed.

**Comment by rockenren** [comment]
Please let me know when fixes will ready for tests.
