### ISSUE TITLE
Query: DELETE FROM mybb_styleyournick  WHERE uid IN()

### ISSUE THREAD

**Issue by rockenren** [Destroy666x/MyBB-Style-Your-Nick#3]
## Your copy of MyBB running on has experienced an error. Details of the error include:

Type: 20
File:  (Line no. 0)
Message
SQL Error: 1064 - You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near ')' at line 1
Query: DELETE FROM mybb_styleyournick  WHERE uid IN()

I've got this error many times. What it could be?

**Comment by rockenren** [comment]
Is this related to clean up task peformed by plugin?
I've searched plugin code and found few strings that look like an in error report:
$db->delete_query('styleyournick', 'uid IN('.implode(',', $todelete).')');
$GLOBALS['db']->delete_query('styleyournick', "uid IN({$del->delete_uids})");
Line 872 and line 881.

**Comment by rockenren** [comment]
This error happens when "Half-hourly User Cleanup" task running.

**Comment by Destroy666x** [comment]
> Is this related to clean up task peformed by plugin?

Yes, the 1.1 developmet version on github hasn't been released nor tested yet. Thanks for report.

**Comment by rockenren** [comment]
Will wait for new version.

**Comment by Destroy666x** [comment]
Should be fixed. As for the new version, 2-3 features are still planned to be added.

**Comment by rockenren** [comment]
It's ok, I've replaced strings from your commit.
Run "Half-hourly User Cleanup" manually, no errors.
