### ISSUE TITLE
Nickname style resets to group defaults after unban

### ISSUE THREAD

**Issue by rockenren** [Destroy666x/MyBB-Style-Your-Nick#4]
Nickname style resets to group defaults after user was unbanned.
How to reproduce:
- let user style his nickname
- ban user
- unban user
- nick style resets to default user group after unban

**Comment by Destroy666x** [comment]
Not a bug at all though. That's how MyBB works - users get their old usergroups after every unban and thus they also have all old permissions, priviledges, etc. If their styling should disappear, change their groups after the unban.

You can even write a small plugin to always put them automatically in chosen `usergroup` and `additionalgroups`, I think.

**Comment by rockenren** [comment]
Yes, they get old usergroups, but isnt nickname style via your plugin append to user?

**Comment by Destroy666x** [comment]
No.. They can be set by users individually but permissions are based on usergroups like everything else. Adding a ban won't remove user's styling either, if that's what you mean, doing that for short temporary bans would be problematic.
